{ created_at: 'Sun Nov 13 00:05:59 +0000 2016',
  id: 797591303303426000,
  id_str: '797591303303426048',
  text: '#lumen vhfaa',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: 
   { id: 95764136,
     id_str: '95764136',
     name: 'Andres Santa Maria',
     screen_name: 'asantamarian',
     location: '-33.444046,-70.597123',
     url: null,
     description: null,
     protected: false,
     verified: false,
     followers_count: 32,
     friends_count: 99,
     listed_count: 3,
     favourites_count: 2,
     statuses_count: 98,
     created_at: 'Wed Dec 09 23:59:10 +0000 2009',
     utc_offset: null,
     time_zone: null,
     geo_enabled: true,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_link_color: '1DA1F2',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     profile_image_url: 'http://pbs.twimg.com/profile_images/1897017771/image_normal.jpg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/1897017771/image_normal.jpg',
     default_profile: true,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  entities: 
   { hashtags: [ [Object] ],
     urls: [],
     user_mentions: [],
     symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'fi',
  timestamp_ms: '1478995559894' }